[build]
publish = "dist"
command = "yarn build"

  [build.environment]
  VITE_GA_TAG = "G-RL3875SQTJ"

[context.deploy-preview.environment]
VITE_MULTINET_HOST = "https://api.multinet.app"
VITE_OAUTH_API_ROOT = "https://api.multinet.app/oauth/"
VITE_OAUTH_CLIENT_ID = "FKSbPC4GNN31E3a6s6f4Uo96gfNfKcGGcEH3K4vq"

[context.production.environment]
VITE_MULTINET_HOST = "https://api.multinet.app"
VITE_OAUTH_API_ROOT = "https://api.multinet.app/oauth/"
VITE_OAUTH_CLIENT_ID = "FKSbPC4GNN31E3a6s6f4Uo96gfNfKcGGcEH3K4vq"
VITE_SENTRY_DSN = "https://ba68e31d5a4341fe949f36012c0a3fd8@o267860.ingest.sentry.io/2103083"
